name: Github Actions demo

on: 
  push:
       branches:
         - 'main'
       paths-ignore:
         - '**/.github'
  pull_request:
       branches:
         - 'main'
  schedule:
       - cron: "15 6 * * 0"  
  workflow_dispatch:


jobs:
      Build:
        runs-on: ubuntu-latest
        steps:
        - run: |
            echo "Event: ${{ github.event_name }}"
            echo "Branch: ${{ github.ref }}"

        - uses: actions/checkout@v4.2.2

        - name: List all files in the repository
          run: tree

      Test:
        runs-on: ubuntu-latest
        environment: Test
        steps:
        - run: |
            echo "Testing..."

      Load-Test:
        runs-on: ubuntu-latest
        environment: Load-Test
        steps:
        - run: |
            echo "Testing"

      Production: 
        runs-on: ubuntu-latest
        environment: Production
        url: https://writeabout.net
        steps:
        - run: |
            echo "Step x deploying..."

            
          
      
         
